steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'git@github.com:usuario/repositorio.git']

serviceAccount: 'build-service-account@seu-projeto.iam.gserviceaccount.com'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
