steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'git@github.com:${_GITHUB_USER}/${_REPO}.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', 'dags/', '${_COMPOSER_BUCKET}']

serviceAccount: '${_SERVICE_ACCOUNT}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

